kind: pipeline
name: default

steps:

- name: docker
  image: plugins/docker
  settings:
    registry: registry.hub.docker.com
    repo: registry.hub.docker.com/dhso/cors-anywhere
    auto_tag: true
    context: ./docker
    dockerfile: ./docker/Dockerfile
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
